FROM ubuntu:14.04

RUN apt-get update && apt-get install -y default-jre wget

RUN wget "http://apache.mirrors.spacedump.net/kafka/0.10.1.1/kafka_2.11-0.10.1.1.tgz" -O /kafka.tgz
RUN mkdir -p /kafka && cd /kafka && tar -xvzf /kafka.tgz --strip 1

ADD ./config/kafka/server.properties /kafka/config/server.properties

EXPOSE 9092

CMD nohup /kafka/bin/kafka-server-start.sh /kafka/config/server.properties
